trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install google-chrome-stable
    sudo apt-get install firefox
    sudo apt-get install testng
    wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo chmod +x chromedriver
    java -cp "./lib/*:./bin" org.testng.TestNG testng.xml
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/results/
    artifactName: Results


