trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install google-chrome-stable
    sudo apt-get install firefox
    sudo apt-get install testng
    sudo apt-get install unzip
    wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
    sudo apt-get update
    sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
    sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
    sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    sudo apt-get -y update
    sudo apt-get -y install google-chrome-stable
    wget -N https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip -P ~/
    unzip ~/chromedriver_linux64.zip -d ~/
    rm ~/chromedriver_linux64.zip
    sudo mv -f ~/chromedriver $(System.DefaultWorkingDirectory)/bin/chromedriver
    sudo chown root:root $(System.DefaultWorkingDirectory)/bin/chromedriver
    sudo chmod 0755 $(System.DefaultWorkingDirectory)/bin/chromedriver
    java -cp "./lib/*:./bin" org.testng.TestNG testng.xml
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/results/
    artifactName: Results


