trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
    SELENIUM_STANDALONE_VERSION=3.9.1
    SELENIUM_SUBDIR=$(echo "$SELENIUM_STANDALONE_VERSION" | cut -d"." -f-2)

    sudo apt-get update
    sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
    sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
    sudo echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    sudo apt-get -y update
    sudo apt-get -y install google-chrome-stable
    sudo apt-get install -y testng
    wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
    unzip ~/chromedriver_linux64.zip -d ~/
    rm ~/chromedriver_linux64.zip
    sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
    sudo chown root:root /usr/local/bin/chromedriver
    sudo chmod 0755 /usr/local/bin/chromedriver

    wget -N https://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
    sudo mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/local/bin/selenium-server-standalone.jar
    sudo chown root:root /usr/local/bin/selenium-server-standalone.jar
    sudo chmod 0755 /usr/local/bin/selenium-server-standalone.jar
    cd /usr/local/bin/
    sudo apt-get install testng
    java -cp "/lib/*:/bin/" org.testng.TestNG testng.xml
    
- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.SourcesDirectory)'
      artifact: 'Results'
      publishLocation: 'pipeline'
  condition: succeededOrFailed()


