trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install google-chrome-stable
    sudo apt-get install firefox
    sudo apt-get install testng
    sudo apt-get install unzip
    wget -N http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip -P ~/
    unzip ~/chromedriver_linux64.zip -d ~/
    rm ~/chromedriver_linux64.zip
    sudo mv -f ~/chromedriver /bin/chromedriver
    java -cp "./lib/*:./bin" org.testng.TestNG testng.xml
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/results/
    artifactName: Results


