trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install google-chrome-stable
    sudo apt-get install firefox
    java -cp "./lib/*:./bin"
    #java org.testng.TestNG testng.xml
    
- task: Ant@1
  inputs:
    buildFile: 'testng.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
   
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/results/
    artifactName: Results


